from tkinter import *
import tkinter as tk
from tkinter import ttk, messagebox

class Inventario(tk.Frame):
    def __init__(self, parent):
        super().__init__(parent)
        self.pack()
        self.widgets()
    def widgets(self):
        #frame1 = tk.Frame(self, bg="blue")
        #frame1.pack()
        #frame1.place(x=0,y=0,width=1100,height=400)
        titulo = tk.Label(self,text="INVENTARIO",bg="white")
        #titulo.pack()
        titulo.place(x=5,y=0,width=1090, height=90)
        lbframe = tk.LabelFrame(self,text="Productos")
        lbframe.place(x=5,y=100,width=400,height=500)
        Label(lbframe,text="Nombre:",bg="#C6D9E3",font="san 14 bold").place(x=10,y=30)
        self.nombre = tk.Entry(lbframe,font="san 14 bold")
        self.nombre.place(x=140,y=20,width=240,height=40)
        Label(lbframe,text="Proveedor:",bg="#C6D9E3",font="san 14 bold").place(x=10,y=80)
        self.proveedor = tk.Entry(lbframe,font="san 14 bold")
        self.proveedor.place(x=140,y=80,width=240,height=40)
        Label(lbframe,text="Precio:",bg="#C6D9E3",font="san 14 bold").place(x=10,y=140)
        self.precio = tk.Entry(lbframe,font="san 14 bold")
        self.precio.place(x=140,y=140,width=240,height=40)
        Label(lbframe,text="Costo:",bg="#C6D9E3",font="san 14 bold").place(x=10,y=200)
        self.costo = tk.Entry(lbframe,font="san 14 bold")
        self.costo.place(x=140,y=200,width=240,height=40)
        Label(lbframe,text="Stock:",bg="#C6D9E3",font="san 14 bold").place(x=10,y=260)
        self.stock = tk.Entry(lbframe,font="san 14 bold")
        self.stock.place(x=140,y=260,width=240,height=40)
        boton_Agregar = tk.Button(lbframe,text="Ingresar",font="san 14 bold",bg="#dddddd").place(x=80,y=340,width=240,height=40)
        boton_Editar = tk.Button(lbframe,text="Editar",font="san 14 bold",bg="#dddddd").place(x=80,y=400,width=240,height=40)
        treeframe = tk.LabelFrame(self,text="Tabla de Productos")
        treeframe.place(x=440,y=100,width=620,height=500)
        scrol_y = tk.Scrollbar(treeframe, orient="vertical")
        scrol_y.pack(side="right", fill=Y)
        scrol_x = tk.Scrollbar(treeframe, orient="horizontal")
        scrol_x.pack(side="bottom", fill=X)
        self.treevie = ttk.Treeview(treeframe, columns=("ID","PRODUCTO","PROVEEDOR","PRECIO","COSTO","STOCK"),
                                    show="headings", height=40, yscrollcommand=scrol_y.set, xscrollcommand=scrol_x.set)
        scrol_y.config(command=self.treevie.yview)
        scrol_x.config(command=self.treevie.xview)
        self.treevie.heading("ID",text="Id")
        self.treevie.heading("PRODUCTO",text="Producto")
        self.treevie.heading("PROVEEDOR",text="Proveedor")
        self.treevie.heading("PRECIO",text="Precio")
        self.treevie.heading("COSTO",text="Costo")
        self.treevie.heading("STOCK",text="Stock")
        self.treevie.column("ID",anchor="center",width=70)
        self.treevie.column("PRODUCTO",anchor="center",width=100)
        self.treevie.column("PROVEEDOR",anchor="center",width=100)
        self.treevie.column("PRECIO",anchor="center",width=70)
        self.treevie.column("COSTO",anchor="center",width=70)
        self.treevie.column("STOCK",anchor="center",width=70)
        self.treevie.pack(expand=TRUE, fill="both")


